### ISSUE TITLE
Images for `run_tests.sh` are missing

### ISSUE THREAD

**Issue by Horgix** [Vermeille/Torchelie#17]
I wanted to run the `run_tests.sh` script at the root of the repo but the images it uses seem to be missing:

- `tests/dream_me.jpg`
- `tests/style.jpg`

While I don't think that committing them in the repo would be a good thing, maybe they can be made available somewhere else? I'll update the README and add an appropriate warning to the test script with how to get the missing files :slightly_smiling_face: I just need to know where we can get them!

**Comment by Vermeille** [comment]
They can belong to the repo and used for demo and display in the README.

I'll make sure the images are okay to go public and commit them ASAP

**Comment by Vermeille** [comment]
These images relate to #24 .

**Comment by Horgix** [comment]
> They can belong to the repo and used for demo and display in the README.
> 
> I'll make sure the images are okay to go public and commit them ASAP

I'd suggest hosting them anywhere else (imgur, personal server, gdrive, whatever) just to avoid starting to bloat the repo with images. In such a project, it can make it heavy to pull faster than expected imho (and once it's in the history... it will stay there)

**Comment by Horgix** [comment]
Closed by 16529e6f67e6d184bc591e8a9f9570e8f77c1522
