### ISSUE TITLE
Remove the `v1.1` branch?

### ISSUE THREAD

**Issue by Horgix** [Vermeille/Torchelie#65]
The [`v1.1` branch](https://github.com/Vermeille/Torchelie/tree/v1.1) is currently329 commits behind master.

I guess it would make sense to remove it? Is there anything so salvage from it?

**Comment by Vermeille** [comment]
Oh hell yeah, we can nuke that thing with ultraviolence!

**Comment by Horgix** [comment]
> Oh hell yeah, we can nuke that thing with ultraviolence!

Cool! Done :heavy_check_mark:
